CREATE TABLE T_ROOM_CONFIG2
(
   class_id varchar(32)
  ,IGROUP 				INTEGER
	,IROW					INTEGER
	,ICOLUMN				INTEGER
	,primary key(class_id,IGROUP)
);

insert into T_ROOM_CONFIG2(class_id,IGROUP, IROW,ICOLUMN) select '001',IGROUP, IROW,ICOLUMN from T_ROOM_CONFIG

alter table T_ROOM_CONFIG2 rename to T_ROOM_CONFIG

CREATE TABLE T_EQUIPMENT_LOCATION_MAP2
(
	class_id varchar(32),
	EQUIPEMNTID 		varchar(32),
	IGROUP 				INTEGER,
	IROW 				INTEGER ,
	ICOLUMN 			INTEGER,
	primary key(EQUIPEMNTID)
);

insert into T_EQUIPMENT_LOCATION_MAP2(class_id,EQUIPEMNTID,IGROUP, IROW,ICOLUMN) select '001',EQUIPEMNTID,IGROUP, IROW,ICOLUMN from T_EQUIPMENT_LOCATION_MAP

alter table T_EQUIPMENT_LOCATION_MAP2 rename to T_EQUIPMENT_LOCATION_MAP
